name: flyvec
channels:
  - conda-forge
  - anaconda
  - fastai
dependencies:
  - pip>=20.0.0
  - python=3.6
  - twine
  - nbdev
  - jedi=0.17.2
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - matplotlib
  - nb_conda
  - pip:
    - dvc[s3] 
