# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"softmax": "00_core.ipynb",
         "normalize_synapses": "00_core.ipynb",
         "FlyVec": "00_core.ipynb",
         "initialize_flyvec": "00_core.ipynb",
         "line2sentences": "01_Tokenizer.ipynb",
         "spattern": "01_Tokenizer.ipynb",
         "strip_punc_unicode": "01_Tokenizer.ipynb",
         "remove_multiple_spaces": "01_Tokenizer.ipynb",
         "space_pat": "01_Tokenizer.ipynb",
         "isnum": "01_Tokenizer.ipynb",
         "process_line": "01_Tokenizer.ipynb",
         "file2tokens": "01_Tokenizer.ipynb",
         "PATCH_DICT": "01_Tokenizer.ipynb",
         "GensimTokenizer": "01_Tokenizer.ipynb"}

modules = ["core.py",
           "tokenizer.py"]

doc_url = "https://bhoov.github.io/flyvec/"

git_url = "https://github.com/bhoov/flyvec/tree/master/"

def custom_doc_links(name): return None
