# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_Train Flyvec.ipynb (unless otherwise specified).

__all__ = ['BIN', 'init']

# Cell
import os
from pathlib import Path
import ctypes
from ctypes import *
import array as arr
import sys
import argparse
import time
import numpy
import flyvec.path_fixes as pf
import subprocess as sp

# Cell
# Load binaries
BIN = pf.CU_BIN

# Cell
from fastcore.script import *

@call_parse
def init():
    sp.call(["sh", str(BIN / "short_make")], cwd=str(BIN))